spring:
  datasource:
    url: jdbc:h2:mem:ahp
    driver-class-name: org.h2.Driver
    username: ahp
    password: simpleAHP
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:db/*.xml

management.endpoints.web.exposure.include: 'health,info'
